---
- name: Clé du dépôt Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Dépôt Docker
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Installer containerd
  ansible.builtin.apt:
    name: containerd.io

- name: Configurer containerd
  ansible.builtin.shell: >
    containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml
    && touch /etc/containerd/.configured
  args:
    creates: /etc/containerd/.configured
  notify: Redémarrer containerd

- name: Démarrer containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: started
